-- Migration number: 0001 	 2025-03-30T11:24:30.365Z

CREATE TABLE Attempts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    -- Epoch is used to count how many times did
    -- a specific channel got a perfect 45, this
    -- is incremented whenever someone gets it.
    epoch INTEGER NOT NULL,
    -- Data from Twitch, refer to their docs.
    broadcaster_user_id TEXT NOT NULL,
    chatter_user_id TEXT NOT NULL,
    -- 45_value is generated by random, difference
    -- is calculated by checking if the value is more
    -- than or less than 45. Lower is better.
    forty_five_value INTEGER NOT NULL,
    forty_five_difference INTEGER NOT NULL,
    -- The exact time a 45 was generated, and is
    -- derived by the database.
    forty_five_timestamp DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);